import { CommentEvent } from "./types";

export const DEFAULT_KEYWORDS = [
  "loud thud",
  "heard it",
  "heard sounds",
  "boom",
  "explosion",
  "explosions",
  "missile",
  "missiles",
  "drone",
  "drones",
  "interception",
  "siren",
  "air defense",
  "thud",
  "blast",
  "shook",
  "shaking",
  "window shook",
  "loud sound",
  "whoosh",
  "wuuush",
  "grrrr",
];

export const SAMPLE_EVENTS: CommentEvent[] = [
  {
    id: "1",
    source: "reddit",
    country: "Bahrain",
    author: "user1",
    text: "Slight thud in Muharraq",
    minutesAgo: 10,
    upvotes: 5,
  },
  {
    id: "2",
    source: "reddit",
    country: "Bahrain",
    author: "user2",
    text: "Heard it",
    minutesAgo: 9,
    upvotes: 3,
  },
  {
    id: "3",
    source: "reddit",
    country: "Bahrain",
    author: "user3",
    text: "Wuuuush sound just now",
    minutesAgo: 8,
    upvotes: 2,
  },
  {
    id: "4",
    source: "reddit",
    country: "Qatar",
    author: "doha_watch",
    text: "Multiple explosions heard in Doha",
    minutesAgo: 7,
  },
  {
    id: "5",
    source: "x",
    country: "UAE",
    author: "@gulfalerts",
    text: "Reports of loud booms in Abu Dhabi",
    minutesAgo: 5,
  },
  {
    id: "6",
    source: "official",
    country: "Bahrain",
    author: "Bahrain Alerts",
    text: "Warning sirens sound only for direct threats to Bahrain",
    minutesAgo: 2,
  },
];